name: Deploy Next.js App

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install --force
    - name: Build app
      run: npm run build
    - name: Deploy app
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: .next/*
        target: /var/www/erp.proplast.et/html
    - name: Add pm2 to PATH
      env:
       PATH: /home/sam/.nvm/versions/node/v16.18.0/bin/pm2:$PATH
    - name: Start app with pm2
      run: pm2 start index.js
